### PR TITLE
Add ignore pattern for .nvmrc

### PR DESCRIPTION
**Pull request by favrik**

### CODE REVIEW

**Comment by cweagans** [comment]
:-1: you should put this (and any other IDE/editor project files or configuration) in your global gitignore.

**Comment by jmolivas** [comment]
Create a global .gitignore file: https://help.github.com/articles/ignoring-files/

**Comment by antillas21** [comment]
my two cents: not everyone has a global `.gitignore` file, and also listing patterns to ignore in a local `.gitignore` file does not add overhead or dependencies to a project.

Anyhow, think this should be left to repo maintainers discresion or project coding guides (if applicable).

What do you guys think?

**Comment by favrik** [comment]
@cweagans can you elaborate on the rationale for not including it in the project `.gitignore`?

Initially, I only added the PR for personal convenience xD, but if you want to keep the `.gitignore` file tidy and pure, I'm definitely ok with creating a global .gitignore.

Thanks!

**Comment by cweagans** [comment]
It just doesn't make sense to include every IDE/editor config under the sun in a .gitignore for every project. It makes so much more sense to centralize that in a global gitignore and keep project .gitignore files to only ignoring specific files for the project.

**Comment by favrik** [comment]
@cweagans yep, I think that makes sense, let's keep it clean.  Thanks!

**Pull request closed without merging**
