### PR TITLE
A new beginning, ReactJS+ES6

### PR DESCRIPTION
**Pull request by antillas21**
Remove all files, 'cause we're Reactifying.
Sets things up wiht React + ES6 + Material UI
- Add README file
- Adds material-ui
- [DRAFT] Sketches homepage

### CODE REVIEW

**Comment by antillas21** [comment]
drupalgenerator

**Comment by jmolivas** [comment]
:+1:

**Comment by antillas21** [comment]
does it mean :shipit:  @jmolivas ? if so, can you do the honors?

**Comment by jmolivas** [comment]
Any thoughts @omero @enzolutions ?

**Comment by jmolivas** [comment]
@antillas21: Thanks for the PR

**Pull request merged**
